//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidatos
    {
        public candidatos()
        {
            this.ofertas = new HashSet<ofertas>();
        }
    
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string DNI { get; set; }
        public int ID_Oficio { get; set; }
        public string Contraseña { get; set; }
    
        public virtual oficio oficio { get; set; }
        public virtual ICollection<ofertas> ofertas { get; set; }
    }
}
