//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoJobs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class infojobsEntities : DbContext
    {
        public infojobsEntities()
            : base("name=infojobsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<candidatos> candidatos { get; set; }
        public DbSet<empresas> empresas { get; set; }
        public DbSet<ofertas> ofertas { get; set; }
        public DbSet<oficio> oficio { get; set; }
    }
}
