//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofertas
    {
        public ofertas()
        {
            this.candidatos = new HashSet<candidatos>();
        }
    
        public int ID_Oferta { get; set; }
        public string NIF_Empresa { get; set; }
        public int ID_Oficio { get; set; }
        public string Descripcion { get; set; }
    
        public virtual empresas empresas { get; set; }
        public virtual oficio oficio { get; set; }
        public virtual ICollection<candidatos> candidatos { get; set; }
    }
}
